// src/lib/components/ui/button.svelte
<script lang="ts" module>
  import { cva, type VariantProps } from "class-variance-authority";

  export const buttonVariants = cva("button", {
    compoundVariants: [
      {
        className: "button--primary-danger",
        intent: "primary",
        status: "danger",
      },
      {
        className: "button--secondary-danger",
        intent: "secondary",
        status: "danger",
      },
      {
        className: "button--tertiary-danger",
        intent: "tertiary",
        status: "danger",
      },
    ],
    defaultVariants: {
      intent: "primary",
      size: "medium",
    },
    variants: {
      fullWidth: {
        true: "button--full-width",
      },
      iconOnly: {
        true: "button--icon-only",
      },
      intent: {
        primary: "button--primary",
        secondary: "button--secondary",
        tertiary: "button--tertiary",
      },
      size: {
        large: "button--large",
        medium: "button--medium",
        small: "button--small",
      },
      status: {
        danger: "button--danger",
      },
    },
  });

  export type ButtonProps = Button.RootProps &
    VariantProps<typeof buttonVariants>;
</script>

<script lang="ts">
  import { Button } from "bits-ui";

  let {
    ref = $bindable(null),
    intent,
    iconOnly,
    fullWidth,
    size,
    status,
    class: className,
    ...props
  }: ButtonProps = $props();
</script>

<Button.Root
  bind:ref
  class={buttonVariants({
    intent,
    iconOnly,
    fullWidth,
    size,
    status,
    className,
  })}
  {...props}
/>

<style>
  :global {
    .button {
      display: inline flex;
      position: relative;
      column-gap: var(--button-column-gap);
      justify-content: center;
      align-items: center;
      transition-duration: 150ms;
      transition-property:
        color, background-color, border-color, outline-color,
        text-decoration-color;
      transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
      cursor: pointer;
      outline: transparent;
      border-radius: calc(infinity * 1px);
      isolation: isolate;
      padding-inline: var(--button-padding-inline);
      padding-block: var(--button-padding-block);
      overflow: hidden;
      font-weight: 500;
      line-height: 1;
      letter-spacing: normal;
      user-select: none;

      &:focus-visible {
        z-index: 10;
        outline-color: var(--color-primary-8);
        outline-style: solid;
        outline-width: 3px;
        outline-offset: 1px;
      }

      svg {
        flex-shrink: 0;
        width: 1em;
        height: 1em;
      }
    }

    .button--primary {
      background-color: var(--color-primary-9);
      color: var(--color-light);

      &:active {
        background-color: var(--color-primary-11);
      }

      &:hover {
        background-color: var(--color-primary-10);
      }
    }

    .button--primary-danger {
      background-color: var(--color-danger-9);
      color: var(--color-light);

      &:active {
        background-color: var(--color-danger-11);
      }

      &:hover {
        background-color: var(--color-danger-10);
      }
    }

    .button--secondary {
      background-color: var(--color-neutral-3);
      color: var(--color-neutral-12);

      &:active {
        background-color: var(--color-neutral-5);
      }

      &:hover {
        background-color: var(--color-neutral-4);
      }
    }

    .button--secondary-danger {
      background-color: var(--color-neutral-3);
      color: var(--color-danger-9);
    }

    .button--tertiary {
      background-color: transparent;
      color: var(--color-neutral-12);

      &:active {
        background-color: var(--color-neutral-5);
      }

      &:hover {
        background-color: var(--color-neutral-4);
      }
    }

    .button--tertiary-danger {
      color: var(--color-danger-9);
    }

    .button--icon-only {
      padding: var(--button-padding-block);
      aspect-ratio: 1 / 1;
    }

    .button--full-width {
      width: 100%;
    }

    .button--danger {
      &:focus-visible {
        outline-color: var(--color-danger-8);
      }
    }

    .button--small {
      --button-padding-block: 0.5em;
      --button-padding-inline: 0.8em;
      --button-column-gap: calc(var(--button-padding-inline) / 2);

      font-size: var(--label-medium);
    }

    .button--medium {
      --button-padding-block: 0.8em;
      --button-padding-inline: 1.1em;
      --button-column-gap: calc(var(--button-padding-inline) / 2);

      font-size: var(--label-large);
    }

    .button--large {
      --button-padding-block: 1.1em;
      --button-padding-inline: 1.4em;
      --button-column-gap: calc(var(--button-padding-inline) / 2);

      font-size: var(--label-large);
    }
  }
</style>

// components/ui/button.tsx
"use client";

import type { Ref } from "react";
import {
  Button as ButtonPrimitive,
  type ButtonProps as ButtonPrimitiveProps,
} from "react-aria-components";
import type { VariantProps } from "tailwind-variants";
import { variant } from "@/lib/utils/tailwind";

const buttonVariants = variant({
  base: "relative isolate inline-flex shrink-0 cursor-pointer pending:cursor-not-allowed select-none items-center justify-center border-1 outline-0 outline-transparent outline-offset-2 pending:brightness-50 transition-all focus-visible:z-10 focus-visible:outline-3 focus-visible:outline-gray-1000 disabled:cursor-not-allowed disabled:brightness-50 [&_svg]:shrink-0",
  variants: {
    fontSize: {
      small: "text-button-12",
      medium: "text-button-14",
      large: "text-button-16",
    },
    intent: {
      primary:
        "border-gray-900 pressed:border-gray-700 bg-gray-1000 pressed:bg-gray-900 text-gray-100 hover:border-gray-700 hover:bg-gray-900",
      secondary:
        "border-gray-400 pressed:border-gray-500 bg-gray-100 pressed:bg-gray-200 text-gray-1000 hover:border-gray-500 hover:bg-gray-200",
      tertiary:
        "border-transparent pressed:border-gray-500 bg-transparent pressed:bg-gray-300 hover:border-gray-500 hover:bg-gray-200",
      warning:
        "border-amber-400 pressed:border-amber-500 bg-amber-800 pressed:bg-amber-700 text-gray-100 hover:border-amber-500 hover:bg-amber-700",
      danger:
        "border-red-400 pressed:border-red-500 bg-red-800 pressed:bg-red-700 text-gray-1000 hover:border-red-500 hover:bg-red-700",
    },
    size: {
      small: "min-h-8 gap-x-1 px-4 has-[>svg]:px-2",
      medium: "h-10 gap-x-1.5 px-5 has-[>svg]:px-2.5",
      large: "h-12 gap-x-2 px-6 has-[>svg]:px-3",
    },
    icon: {
      true: "p-0!",
    },
    shape: {
      square: "rounded-md",
      circle: "rounded-full",
    },
  },
  compoundVariants: [
    {
      className: "[&_svg]:size-3",
      fontSize: "small",
    },
    {
      className: "[&_svg]:size-3.5",
      fontSize: "medium",
    },
    {
      className: "[&_svg]:w-4",
      fontSize: "large",
    },
    {
      className: "size-8 [&_svg]:size-3",
      icon: true,
      size: "small",
    },
    {
      className: "size-10 [&_svg]:size-3.5",
      icon: true,
      size: "medium",
    },
    {
      className: "size-12 [&_svg]:size-4",
      icon: true,
      size: "large",
    },
  ],
  defaultVariants: {
    intent: "primary",
    size: "medium",
    fontSize: "medium",
    shape: "square",
  },
});

type ButtonProps = {
  ref?: Ref<HTMLButtonElement>;
} & Omit<ButtonPrimitiveProps, "className"> &
  VariantProps<typeof buttonVariants>;

export function Button({
  intent,
  fontSize,
  size,
  icon,
  shape,
  ref,
  ...props
}: ButtonProps) {
  return (
    <ButtonPrimitive
      className={buttonVariants({
        fontSize,
        size,
        intent,
        icon,
        shape,
      })}
      ref={ref}
      {...props}
    >
      {(values) => (
        <>
          {typeof props.children === "function"
            ? props.children(values)
            : props.children}
        </>
      )}
    </ButtonPrimitive>
  );
}
